
/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & typeof globalThis;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching for audio files (MP3, OGG) from any source for offline playback
registerRoute(
  ({ url }) => url.href.endsWith('.mp3') || url.href.endsWith('.ogg') || url.href.includes('mp3'),
  new CacheFirst({
    cacheName: 'nasheed-audio-general',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache covers and images
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'app-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
    ],
  })
);

// Listen for push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'سندك';
    const options = {
      body: data.body || 'لديك تنبيه جديد من سندك',
      icon: 'https://cdn-icons-png.flaticon.com/512/2903/2903531.png',
      badge: 'https://cdn-icons-png.flaticon.com/512/2903/2903531.png',
      data: data.data || {},
      tag: data.tag || 'general-notification',
      requireInteraction: data.requireInteraction || false
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (e) {
    console.error('Push handling error:', e);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  // Open the app
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        let client = clientList[0];
        for (let i = 0; i < clientList.length; i++) {
          if (clientList[i].focused) {
            client = clientList[i];
          }
        }
        return client.focus();
      }
      return self.clients.openWindow('/');
    })
  );
});
